[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[[redirects]]
  from = "/api/leaderboard"
  to = "/.netlify/functions/leaderboard"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
